BackMeow/Controllers/ZipCodeController.cs
using StoreDB.Repositories;
using System.Text;
using System.Web.Mvc;

namespace BackMeow.Controllers
{
    public class ZipCodeController : Controller
    {
        private readonly ZipCodeService _ZipCodeService;

        public ZipCodeController()
        {
            var unitOfWork = new EFUnitOfWork();
            _ZipCodeService = new ZipCodeService(unitOfWork);
        }

        // 日後改成 bootstrap https://www.w3schools.com/bootstrap/bootstrap_dropdowns.asp

        /// <summary>
        /// Gets the city drop downlist.
        /// </summary>
        /// <param name="selectedCity">The selected city.</param>
        /// <returns></returns>
        public ActionResult GetCityDropDownlist(string selectedCity)
        {
            StringBuilder sb = new StringBuilder();

            var cities = _ZipCodeService.GetAllCityDictinoary();

            if (string.IsNullOrWhiteSpace(selectedCity))
            {
                foreach (var item in cities)
                {
                    sb.AppendFormat("<option value=\"{0}\">{1}</option>", item.Key, item.Value);
                }
            }
            else
            {
                foreach (var item in cities)
                {
                    sb.AppendFormat("<option value=\"{0}\" {2}>{1}</option>",
                        item.Key,
                        item.Value,
                        item.Key.Equals(selectedCity) ? "selected=\"selected\"" : "");
                }
            }
            return Content(sb.ToString());
        }

        /// <summary>
        /// Gets the county drop downlist.
        /// </summary>
        /// <param name="cityName">Name of the city.</param>
        /// <param name="selectedCounty">The selected county.</param>
        /// <returns></returns>
        public ActionResult GetCountyDropDownlist(string cityName, string selectedCounty)
        {
            if (!string.IsNullOrWhiteSpace(cityName))
            {
                StringBuilder sb = new StringBuilder();

                var counties = _ZipCodeService.GetCountyByCityName(cityName);

                if (string.IsNullOrWhiteSpace(selectedCounty))
                {
                    foreach (var item in counties)
                    {
                        sb.AppendFormat("<option value=\"{0}\">{1}</option>",
                            item.Key,
                            string.Concat(item.Key, " ", item.Value)
                        );
                    }
                }
                else
                {
                    foreach (var item in counties)
                    {
                        sb.AppendFormat("<option value=\"{0}\" {2}>{1}</option>",
                            item.Key,
                            string.Concat(item.Key, " ", item.Value),
                            item.Key.Equals(selectedCounty) ? "selected=\"selected\"" : "");
                    }
                }

                return Content(sb.ToString());
            }
            return Content(string.Empty);
        }
    }
}

BackMeow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>非喵布可 😺</title>
    @Styles.Render("~/Content/css")
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="~/Content/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/vendor/linearicons/style.css">
    <link rel="stylesheet" href="~/Content/vendor/chartist/css/chartist-custom.css">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/Content/css/main.css">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="~/Content/css/demo.css">
    <!-- GOOGLE FONTS -->
    <link href="~/Content/css/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/css/demo.css" rel="stylesheet" />
    <!--DatePicker css-->
</head>
<body>
    <div class="modal"><!-- Place at bottom of page --></div>
    <div id="wrapper">
        <!-- NAVBAR -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="brand">
                <a href="/Home/Index">
                    <img src="~/Content/img/if_cat_track-24_302350.png" alt="非喵布可">非喵布可
                </a>
            </div>
            <div class="container-fluid">

                <div class="navbar-btn">
                    <button type="button" class="btn-toggle-fullwidth">
                        <i class="lnr lnr-arrow-left-circle">@*第一次載入顯示選單，其餘皆縮小選單*@</i>
                    </button>
                </div>

                <div id="navbar-menu">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
                                <i class="lnr lnr-alarm"></i>
                                <span class="badge bg-danger">5</span>
                            </a>
                            <ul class="dropdown-menu notifications">
                                <li><a href="#" class="notification-item"><span class="dot bg-warning"></span>System space is almost full</a></li>
                                <li><a href="#" class="notification-item"><span class="dot bg-danger"></span>You have 9 unfinished tasks</a></li>
                                <li><a href="#" class="notification-item"><span class="dot bg-success"></span>Monthly report is available</a></li>
                                <li><a href="#" class="notification-item"><span class="dot bg-warning"></span>Weekly meeting in 1 hour</a></li>
                                <li><a href="#" class="notification-item"><span class="dot bg-success"></span>Your request has been approved</a></li>
                                <li><a href="#" class="more">See all notifications</a></li>
                            </ul>
                        </li>
                        @Html.Partial("_LoginPartial")
                        @*<li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <img src="assets/img/user.png" class="img-circle" alt="Avatar"> <span>Samuel</span>
                                    <i class="icon-submenu lnr lnr-chevron-down"></i>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="#"><i class="lnr lnr-user"></i> <span>My Profile</span></a></li>
                                    <li><a href="#"><i class="lnr lnr-envelope"></i> <span>Message</span></a></li>
                                    <li><a href="#"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>
                                    <li>
                                        <a href="#" class="logout">
                                            <i class="lnr lnr-exit"></i>
                                            <span>Logout</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>*@
                    </ul>
                </div>
            </div>
        </nav>
        <!-- END NAVBAR -->
        <!-- LEFT SIDEBAR -->
        @Html.Action("SideBarContent", "Home")
        @*<div class="customersidebar">
            </div>*@
        @*@Html.Partial("_Sidebar")*@

        <!-- END LEFT SIDEBAR -->
        <!-- MAIN -->
        <div class="main">
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">
                    <!-- OVERVIEW -->
                    <div class="panel panel-headline">
                        @RenderBody()
                    </div>
                    <!-- END OVERVIEW -->
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
        <!-- END MAIN -->
        <div class="clearfix"></div>
        <div class="modal"><!-- Place at bottom of page --></div>
        <footer>
            <div class="container-fluid">
                <p class="copyright">&copy; @DateTime.Now.Year - 非喵不可 <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    @*<script src="~/Scripts/jquery.validate.js"></script>*@
    <script src="~/Scripts/jquery.validate.min.js"></script>
    @*<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>*@
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
    @*<script src="~/Scripts/jquery-3.3.1.min.js"></script>*@

    <script src="~/Scripts/jquery-ui.js"></script>
    <script src="~/Content/vendor/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/Content/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
    <script src="~/Content/vendor/chartist/js/chartist.min.js"></script>
    <script src="~/Content/vendor/klorofil-common.js"></script>
    <script src="~/Scripts/PublicBase.js"></script>
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function () {

            //$('.customersidebar').load('/Home/SideBarContent/');
            $(".collapse").on('click', function () {
                $(this).addClass("active");
            }) //選單

            //$(".logout").on('click', function () {
            //    alert('logout!!');
            //    $.ajax({
            //        type: "POST",
            //        url: "/Account/LogOff" ,
            //        contentType: "application/json; charset=utf-8",
            //        dataType: "json",
            //        success: function (response) {
            //        },
            //        failure: function (response) {
            //            alert(response.responseText);
            //        },
            //        error: function (response) {
            //            alert(response.responseText);
            //        }
            //    });
            //})

            $(".table-hover").on('click', '.btn-danger', function () {
                var currentRow = $(this).closest("tr"); // get current row 1st table cell TD value
                @*showconfirm(currentRow.find(".primarkeyvalue").val(), '@Orignal_Page.MA_DebtManagementData');*@
            });

            //設定中文語系
            $.datepicker.regional['zh-TW'] = {
                dayNames: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
                dayNamesMin: ["日", "一", "二", "三", "四", "五", "六"],
                monthNames: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
                monthNamesShort: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
                prevText: "上月",
                nextText: "次月",
                weekHeader: "週"
            };
            //將預設語系設定為中文
            $.datepicker.setDefaults($.datepicker.regional["zh-TW"]);
            //套用到表單

            //日曆
            $('.datepicker').datepicker({
                dateFormat: 'yy/mm/dd',
                changeMonth: true,
                changeYear: true
            }); //Initialise any date pickers

            //日曆加上時間
            //$('.datetimepicker').datetimepicker({
            //    dateFormat: 'yy/mm/dd HH:mm',
            //    changeMonth: true,
            //    changeYear: true
            //});
        });

        $body = $("body");

        $(document).on({
            ajaxStart: function () { $body.addClass("loading"); },
            ajaxStop: function () { $body.removeClass("loading"); }
        });

        function showconfirm(Guid, Pages, ControllerName, TableName) {
            var $dialog = $('<div id="dialog-confirm" ></div>');
            var text01 = $dialog.html('<p><span class="ui-icon ui-icon-alert" style="float:left; margin:12px 12px 20px 0;"></span>刪除將無法回復，確定刪除嗎?</p>');
            var text02 = text01.dialog({
                    autoOpen: false,
                    resizable: false,
                    modal: true,
                    width: '300',
                    title: "刪除提醒視窗",
                    buttons: {
                        "確認刪除": function () {
                            $(this).dialog("close");
                            Delete(Guid, Pages, ControllerName, TableName);
                        },
                        "取消": function () {
                            $(this).dialog("close");
                        }
                    }
                });
            $dialog.dialog('open');
        }

        function showDialog(message, reloadtrue,responseViewModel) {
            var $dialog = $('<div id="dialog" ></div>')
                .html(message)
                .dialog({
                    autoOpen: false,
                    resizable: false,
                    modal: true,
                    width: '200',
                    title: "訊息視窗",
                    buttons: {
                        "確認": function () {
                            $(this).dialog("close");
                            if (reloadtrue == true) { //刪除後需要Reload
                                //location.reload();
                                $("#ReloadBlock").html(responseViewModel);
                            }
                            //else {
                            //    location.reload();
                            //}
                        }
                    }
                });
            $dialog.dialog('open');
        }

        function Delete(Guid, Pages, ControllerName, TableName) {
            $.ajax({
                type: 'POST',
                url: '/' + ControllerName + '/Delete' ,
                dataType: "json",
                data: {
                    guid: Guid,
                    actionTable: TableName
                },
                success:
                function (response) {
                    //if (response.result != null) {
                    if (response.result) {
                        showDialog(response.result, true, response.viewModel);
                    } else {
                        location.reload();
                    }
                },
                error: function () { showDialog('未知的錯誤!', false); }
            });
        }
    </script>
</body>
</html>

BackMeow/Views/Shared/_LayoutEmpty.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="~/Content/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/vendor/linearicons/style.css">
    <link rel="stylesheet" href="~/Content/vendor/chartist/css/chartist-custom.css">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/Content/css/main.css">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="~/Content/css/demo.css">
    <!-- GOOGLE FONTS -->
    <link href="~/Content/css/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/css/demo.css" rel="stylesheet" />
    <!--DatePicker css-->
</head>
<body>
    <div class="modal"><!-- Place at bottom of page --></div>

    <div id="wrapper">
        <!-- NAVBAR -->
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="brand">
                <a href="/Home/Index">
                    <img src="~/Content/img/if_cat_track-24_302350.png" alt="非喵布可">非喵布可
                </a>
            </div> 
        </nav>
        <!-- END NAVBAR -->
        <!-- LEFT SIDEBAR --> 

        <!-- END LEFT SIDEBAR -->
        <!-- MAIN -->
        <div class="main">
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">
                    <!-- OVERVIEW -->
                    <div class="panel panel-headline">
                        @RenderBody()
                    </div>
                    <!-- END OVERVIEW -->
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
        <!-- END MAIN -->
        <div class="clearfix"></div>
        <div class="modal"><!-- Place at bottom of page --></div>
        <footer>
            <div class="container-fluid">
                <p class="copyright">&copy; @DateTime.Now.Year - 我的 ASP.NET MVC 應用程式 <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.2.1.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
    <script src="~/Content/vendor/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/Content/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
    <script src="~/Content/vendor/chartist/js/chartist.min.js"></script>
    <script src="~/Content/vendor/klorofil-common.js"></script>
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function () {

            $(".logout").on('click', function () {
                alert('logout!!');
                $.ajax({
                    type: "POST",
                    url: "/Account/LogOff",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (response) {
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    },
                    error: function (response) {
                        alert(response.responseText);
                    }
                });
            })
        }); 
    </script>

</body>
</html>

BackMeow/Views/Shared/_TaiwanZipCode.cshtml
<script src="~/Scripts/TaiwanZipCode.js"></script>
<script type="text/javascript">
    $(function () {
        //var options = {
        //        CityID: '縣市下拉選單 Tag ID',
        //        CountyID: '鄉鎮市區下拉選單 Tag ID',
        //        SelectedCity: '已選擇縣市',
        //        SelectedCounty: '已選擇鄉鎮市區'
        //    };
        //var Items = $('#TESTCityDDL').val;
        var ActionUrls =
        {
          GetCityDropDownlist: '@Url.Action("GetCityDropDownlist", "ZipCode", new { Area = "" })',
          GetCountyDropDownlist: '@Url.Action("GetCountyDropDownlist", "ZipCode", new { Area = "" })'
        };
        TaiwanZipCode.Initialize(ActionUrls);
        //TaiwanZipCode.options.CityID = "91";Items;
    });
</script>

BackMeow/Views/Shared/_UploadFiles.cshtml
@model IEnumerable<StoreDB.Model.Partials.PictureInfo>
@{
    ViewBag.Title = "";
    Layout = null;
}
<link href="~/Content/lightbox.css" rel="stylesheet" />
<link href="~/Content/ScrollbarStyle.css" rel="stylesheet" />
<link href="~/Content/jquery.mCustomScrollbar.css" rel="stylesheet" />

<div id="demo">
    <section id="examples" class="snap-scrolling-example">

        <!-- content -->
        <div id="content-1" class="content horizontal-images">
            <ul>
                @foreach (var item in Model)
                {
                    <li class="lightboxcontainer">
                        <a class="example-image-link" href="@item.PictureUrl@item.PictureName@item.FileExtension" data-lightbox="example-set" data-title="">
                            <img class="example-image" src="@item.PictureUrl@item.PictureName@item.FileExtension" alt="" />
                        </a>
                        <div class="middle">
                            <div class="text" id="@item.PicID">刪除</div>
                        </div>
                    </li>
                }
            </ul>
        </div>
    </section>
</div>
@*}*@

@*<script src="~/Scripts/lightbox-plus-jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="~/Scripts/jquery-1.10.2.min.js"><\/script>')</script>
    <script src="~/Scripts/jquery.mCustomScrollbar.concat.min.js"></script>*@
@*必須放在上一層*@

<script>
    (function ($) {
        $(window).on("load", function () {

            var amount = Math.max.apply(Math, $("#content-1 li").map(function () { return $(this).outerWidth(true); }).get());

            $("#content-1").mCustomScrollbar({
                axis: "x",
                theme: "inset",
                advanced: {
                    autoExpandHorizontalScroll: true
                },
                scrollButtons: {
                    enable: true,
                    scrollType: "stepped"
                },
                keyboard: { scrollType: "stepped" },
                snapAmount: amount,
                mouseWheel: { scrollAmount: amount }
            });

        });
    })(jQuery);

    $(".text").click(function () {
        showconfirm(this.id, 'false', 'StaticHtml', 'PictureInfo');
    })

//$(".lightboxcontainer")
//    .on("mouseenter", function () {
//        //alert('滑鼠移入');
//        //$("p:first", this).text("mouse enter");
//    })
//    .on("mouseleave", function () {
//        //alert('out');
//        //$("p:first", this).text("mouse leave");
//        //$("p:last", this).text(++n);
//    });
</script>