BackMeow/Controllers/ActivityController.cs
using BackMeow.Models.ViewModel;
using BackMeow.Service;
using StoreDB.Enum;
using StoreDB.Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace BackMeow.Controllers
{
    public class ActivityController : Controller
    {
        private readonly ActivitiesService _ActivityService;
        private string FileUrl = WebConfigurationManager.AppSettings["UploadFileUrl"];
        private string _signInManager;

        public ActivityController()
        {
            var unitOfWork = new EFUnitOfWork();
            _ActivityService = new ActivitiesService(unitOfWork);
        }

        public string SignInManagerName
        {
            get
            {
                return _signInManager ?? HttpContext.User.Identity.Name.ToString();
            }
            private set
            {
                _signInManager = value;
            }
        }

        // GET: Activity
        [HttpGet]
        public ActionResult ActivitiesList(ActitiesViewModel ViewModel, int page = 1)
        {
            ActitiesViewModel ResultViewModel;
            ActitiesViewModel searchBlock = (ActitiesViewModel)TempData["ActitiesSelect"];
            if (searchBlock == null) /*空*/
            {
                ResultViewModel = _ActivityService.GetActitiesListViewModel(new ActitiesListHeaderViewModel(), page);
            }
            else
            {
                ResultViewModel = _ActivityService.GetActitiesListViewModel(searchBlock.Header, page);
            }
            return View(ResultViewModel);
        }

        [HttpPost]
        public ActionResult ActivitiesList(ActitiesViewModel ViewModel)
        {
            ActitiesViewModel ResultViewModel = _ActivityService.GetActitiesListViewModel(ViewModel.Header);
            TempData["ActitiesSelect"] = ResultViewModel;
            return View(ResultViewModel);
        }

        #region 藉由ID取得活動項目

        [HttpGet]
        public ActionResult ActivitiesMain(DataAction ActionType, string guid, string selectCreateTime,
            string selectTitleName, string selectHtmlContext, string selectStartDate, string selectEndDate, int pages = 1)
        {
            TempData["DataAction"] = ActionType;
            ActitiesDetailViewModel data = new ActitiesDetailViewModel();
            data = _ActivityService.ReturnActitiesDetailViewModel(ActionType, guid);

            #region KeepSelectBlock

            pages = pages == 0 ? 1 : pages;
            TempData["ActitiesSelect"] = new ActitiesViewModel()
            {
                Header = new ActitiesListHeaderViewModel()
                {
                    CreateTime = selectCreateTime,
                    EndDate = selectEndDate,
                    HtmlContext = selectHtmlContext,
                    StartDate = selectStartDate,
                    TitleName = selectTitleName
                },
                page = pages
            };

            #endregion KeepSelectBlock

            return View(data);
        }

        [HttpPost]
        //[ValidateFile] //上傳照片 日後將此功能抽出 ,日後改使用 MVC File upload unobtrusive validation
        public ActionResult ActivitiesMain(DataAction actions, ActitiesDetailViewModel ActitiesViewModel,
            IEnumerable<HttpPostedFileBase> upload)
        {
            #region KeepSelectBlock

            TempData["DataAction"] = actions;
            TempData["ActitiesSelect"] = (ActitiesViewModel)TempData["ActitiesSelect"];

            #endregion KeepSelectBlock

            if (ModelState.IsValid)
            {
                if (actions == DataAction.Create) //建立資料
                {
                    ActitiesViewModel.ActivityID = Guid.NewGuid().ToString().ToUpper();
                    ActitiesViewModel.PicGroupID = Guid.NewGuid().ToString().ToUpper();
                    //TempData["message"] = _ActivityService.Create(ActitiesViewModel, SignInManagerName);
                }
                else //更新資料
                {
                    //TempData["message"] = _ActivityService.Update(ActitiesViewModel, SignInManagerName);
                }

                #region 上傳照片 日後將此功能抽出

                if (upload.Where(s => s != null).Count() > 0)
                {
                    bool UploadResult = UploadFile(upload, ActitiesViewModel.PicGroupID.ToString());
                    if (UploadResult)
                    {
                        //存入DB
                        _ActivityService.CreatePictureInfo(upload, Guid.Parse(ActitiesViewModel.PicGroupID), SignInManagerName);
                    }
                }

                #endregion 上傳照片 日後將此功能抽出

                _ActivityService.Save();
            }

            // 顯示資料
            ActitiesViewModel = _ActivityService.ReturnActitiesDetailViewModel(actions, ActitiesViewModel.ActivityID);
            return View(ActitiesViewModel);
        }

        /// <summary>
        /// Uploads the file. 上傳照片 日後將此功能抽出 ,日後改使用 MVC File upload unobtrusive validation
        /// </summary>
        /// <param name="upload">The upload.</param>
        /// <returns></returns>
        private bool UploadFile(IEnumerable<HttpPostedFileBase> upload, string FolderName)
        {
            bool TmpResult = false;
            try
            {
                if (upload != null)
                {
                    if (upload.Count() > 0)
                    {
                        string savePath = Server.MapPath(FileUrl) + FolderName;
                        if (!Directory.Exists(savePath))
                        {
                            //If Directory (Folder) does not exists. Create it.
                            Directory.CreateDirectory(savePath);
                        }
                        foreach (var uploadFile in upload)
                            if (uploadFile.ContentLength > 0 && uploadFile.FileName.Length < 20)
                            {
                                string N_savePath = savePath + "\\" + uploadFile.FileName;
                                uploadFile.SaveAs(N_savePath);
                                TmpResult = true;
                            }
                    }
                }
            }
            catch (IOException e)
            {
            }
            return TmpResult;
        }

        #endregion 藉由ID取得活動項目
    }
}

BackMeow/Controllers/SystemController.cs
using BackMeow.Filters;
using BackMeow.Models;
using BackMeow.Models.ViewModel;
using BackMeow.Service;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using StoreDB;
using StoreDB.Enum;
using StoreDB.Helper;
using StoreDB.Model.ViewModel;
using StoreDB.Repositories;
using StoreDB.Service;
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BackMeow.Controllers
{
    [Authorize]
    public class SystemController : Controller
    {
        private Utility _utility = new Utility();
        private readonly AspNetUsersService _UserService;
        private readonly MemberService _MemberService;
        private readonly LoggingService _logSvc;
        private string _signInManagerNames;
        private readonly string _actionName;
        private readonly string _controllerName;
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        private MenuSideListService _menuSide;
        private PublicService _publicService;
        //private ReturnMsg _ReturnMsg;

        public SystemController()
        {
            var unitOfWork = new EFUnitOfWork();
            _UserService = new AspNetUsersService(unitOfWork);
            _MemberService = new MemberService(unitOfWork);
            _logSvc = new LoggingService(unitOfWork);
            _menuSide = new MenuSideListService(unitOfWork);
            _publicService = new PublicService();
            // _ReturnMsg = new ReturnMsg();
            _actionName = "";// this.ControllerContext.RouteData.Values["action"].ToString();
            _controllerName = "";// this.ControllerContext.RouteData.Values["controller"].ToString();
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        /// <summary>
        /// 藉由登入名稱取得ID.
        /// </summary>
        public string SignInManagerId
        {
            get
            {
                _UserService.UserName = HttpContext.User.Identity.Name.ToString(); //登入的使用者帳號
                return _UserService.GetAspNetUserBySelectPramters().Id;
            }
            private set
            {
                _signInManagerNames = value;
            }
        }

        // GET: System

        #region 後台使用者管理

        #region List - 取得所有後台使用者清單

        /// <summary>
        /// Systems the roles.
        /// </summary>
        /// <param name="ViewModel">The view model.</param>
        /// <param name="page">The page.</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult SystemRoles(int page = 1)
        {
            SystemRolesViewModel ResultViewModel;
            SystemRolesViewModel searchBlock = (SystemRolesViewModel)TempData["SystemRolesSelect"];
            if (searchBlock == null) /*空*/
            {
                ResultViewModel = _UserService.GetSystemRolesListViewModel(new SystemRolesListHeaderViewModel(), page);
            }
            else
            {
                ResultViewModel = _UserService.GetSystemRolesListViewModel(searchBlock.Header,
                    page > searchBlock.page ?
                            page : searchBlock.page);
                SystemRolesKeepSelectBlock(ResultViewModel, DataAction.Read);
            }

            return View(ResultViewModel);
        }

        /// <summary>
        /// Systems the roles.
        /// </summary>
        /// <param name="ViewModel">The view model.</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SystemRoles(SystemRolesViewModel ViewModel, int page = 1)
        {
            SystemRolesViewModel ResultViewModel = _UserService.GetSystemRolesListViewModel(ViewModel.Header);
            SystemRolesKeepSelectBlock(ResultViewModel, DataAction.Read);
            return View(ResultViewModel);
        }

        #endregion List - 取得所有後台使用者清單

        #region Main - 明細內容動作

        /// <summary>
        /// 藉由ID取得後台使用者
        /// </summary>
        /// <param name="ActionType">Type of the action.</param>
        /// <param name="guid">The unique identifier.</param>
        /// <param name="selectEmail">The select email.</param>
        /// <param name="selectUserName">Name of the select user.</param>
        /// <param name="pages">The pages.</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult SystemRolesMain(DataAction ActionType, string guid, string selectEmail, string selectUserName, int pages = 1)
        {
            AspNetUsersDetailViewModel data = new AspNetUsersDetailViewModel();
            if (ActionType == DataAction.Update)
            {
                data = _UserService.ReturnAspNetUsersDetail(ActionType, guid);
            }

            #region KeepSelectBlock

            TempData["Actions"] = ActionType;
            pages = pages == 0 ? 1 : pages;
            TempData["SystemRolesSelect"] = new SystemRolesViewModel()
            {
                Header = new SystemRolesListHeaderViewModel()
                {
                    Email = selectEmail,
                    UserName = selectUserName
                },
                page = pages
            };

            #endregion KeepSelectBlock

            return View(data);
        }

        /// <summary>
        /// Systems the roles main.
        /// </summary>
        /// <param name="AspNetUsersModel">The ASP net users model.</param>
        /// <param name="actions">The actions.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ModelStateExclude]
        public async Task<ActionResult> SystemRolesMain(AspNetUsersDetailViewModel AspNetUsersModel, DataAction actions)//, DataAction actions)
                                                                                                                        //(FormCollection AspNetUsersModel,string guid) //,
        {
            bool boolResult = true; // 取決於導向頁面, True = 返回SystemRoles, False = 停在本頁
            string thisUserID; //暫存 使用者ID
            SystemRolesViewModel searchBlock = (SystemRolesViewModel)TempData["SystemRolesSelect"];

            // KeepSelectBlock
            SystemRolesKeepSelectBlock(searchBlock, actions);

            // STEP 1. 前端驗證是否通過
            if (ModelState.IsValid)
            {
                // STEP 2. 建立容器 user
                var user = new ApplicationUser
                {
                    UserName = AspNetUsersModel.UserName,
                    Email = AspNetUsersModel.Email,
                    PhoneNumber = AspNetUsersModel.PhoneNumber,
                    UpdateTime = AspNetUsersModel.UpdateTime,
                    CreateTime = AspNetUsersModel.CreateTime,
                    UpdateUser = SignInManagerId,
                    Status = true
                };

                if (actions == DataAction.Create)
                {
                    #region STEP 3. 判斷動作, [新增]

                    user.CreateUser = SignInManagerId;
                    user.Id = Guid.NewGuid().ToString().ToUpper();
                    _UserService.UserName = user.UserName;
                    _UserService.UserEmail = user.Email;

                    // STEP 4. 該使用者資訊是否存在資料庫, null才可繼續建立
                    if (_UserService.GetAspNetUserBySelectPramters() == null)
                    {
                        var result = await UserManager.CreateAsync(user, AspNetUsersModel.Password);
                        if (result.Succeeded)
                        {
                            //建立使用者應要把 MenuTree 權限也寫入!
                            _UserService.CreateUserMenuTree(user.Id);
                            TempData["message"] = EnumHelper.GetEnumDescription(DataAction.CreateScuess);
                            thisUserID = user.Id;
                            // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                            // 傳送包含此連結的電子郵件
                            //string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                            //var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                            //await UserManager.SendEmailAsync(user.Id, "確認您的帳戶", "請按一下此連結確認您的帳戶 <a href=\"" + callbackUrl + "\">這裏</a>");
                        }
                        else
                        {
                            // 建立失敗, 回傳錯誤訊息
                            AddErrors(result);
                            boolResult = false;
                        }
                    }
                    else
                    {
                        // 建立失敗, 回傳錯誤訊息
                        CustomerIdentityError(EnumHelper.GetEnumDescription(DataAction.CreateFailReapet));
                        boolResult = false;
                    }

                    #endregion STEP 3. 判斷動作, [新增]
                }
                else if (actions == DataAction.Update)
                {
                    #region STEP 3. 判斷動作, [更新]

                    if (!string.IsNullOrEmpty(AspNetUsersModel.Old_Password) &&
                        !string.IsNullOrEmpty(AspNetUsersModel.Password))
                    {
                        bool passwordIsEdit = false;
                        try
                        {

BackMeow/Views/Activity/ActivitiesList.cshtml
@using PagedList.Mvc;
@using StoreDB.Enum;
@model BackMeow.Models.ViewModel.ActitiesViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>活動紀錄管理</h2>

@using (Html.BeginForm("ActivitiesList", "Activity", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="control-group">
        <label class="control-label" for="CityDDL">縣市</label>
        <div class="controls">
            <select id="CityDDL"></select>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="CountyDDL">鄉鎮市區</label>
        <div class="controls">
            <select id="CountyDDL"></select>
        </div>
    </div>
    @Html.HiddenFor(model => model.page)
    <div class="row">
        <div class="col-md-12">
            <!-- PANEL DEFAULT -->
            <div class="panel">
                <div class="panel-heading">
                    <h5 class="widget-title"></h5>
                    <button type="button" class="btn-toggle-collapse">
                        <i class="lnr lnr-chevron-up"></i>
                        活動紀錄管理 查詢區
                    </button>
                    @*<div class="right">
                            <button type="button" onclick="location.href='location.href='@Url.Action("SystemRolesMain", "System",
                                           new { ActionType = DataAction.Create })'">
                                <i class="fa fa-plus-square"></i>新增
                            </button>
                        </div>*@
                </div>
                <div style="overflow: auto;">
                    <div class="panel-body">
                        @Html.LabelFor(model => model.Header.TitleName, htmlAttributes: new { @class = "col-md-2 control-label" })
                        <div class="col-md-3">
                            <input class="form-control" id="select_TitleName" name="Header.TitleName" placeholder="請輸入 @Html.DisplayNameFor(model => model.Header.TitleName)"
                                   type="text" value="@Model.Header.TitleName">
                        </div>
                        @Html.LabelFor(model => model.Header.CreateTime, htmlAttributes: new { @class = "col-md-2 control-label" })
                        <div class="col-md-3">
                            <input class="form-control" id="select_CreateTime" name="Header.CreateTime" placeholder="請輸入 @Html.DisplayNameFor(model => model.Header.CreateTime)"
                                   type="text" value="@Model.Header.CreateTime">
                        </div>
                    </div>
                    <div class="panel-body">
                        @Html.LabelFor(model => model.Header.StartDate, htmlAttributes: new { @class = "col-md-2 control-label" })
                        <div class="col-md-3">
                            <input class="form-control" id="select_StartDate" name="Header.StartDate" placeholder="請輸入 @Html.DisplayNameFor(model => model.Header.StartDate)"
                                   type="text" value="@Model.Header.StartDate">
                        </div>
                        <label class="col-md-1">至</label>
                        @Html.LabelFor(model => model.Header.EndDate, htmlAttributes: new { @class = "col-md-1 control-label" })
                        <div class="col-md-3">
                            <input class="form-control" id="select_EndDate" name="Header.EndDate" placeholder="請輸入 @Html.DisplayNameFor(model => model.Header.EndDate)"
                                   type="text" value="@Model.Header.EndDate">
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <button type="button" id="Create" class="btn btn-default pull-right">
                        @*onclick="location.href='@Url.Action("SystemRolesMain", "System",
                            new { ActionType = DataAction.Create })'"*@
                        <i class="fa fa-plus-square"></i> 新增
                    </button>
                    <button type="submit" class="btn btn-default pull-right">
                        <i class="fa fa-search lg"></i>查詢
                    </button>
                </div>
            </div>
            <!-- END PANEL DEFAULT -->
        </div>
    </div>
}
<div class="row">
    <div class="col-md-12">
        @Html.Partial("_ActivitiesList", Model.Content_List)
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        @Html.PagedListPager(Model.Content_List, page => Url.Action("SystemRoles", new { ViewModel = @Model, page }),
                                                                                                                                                             PagedListRenderOptions.ClassicPlusFirstAndLast)
    </div>
</div>

@section Scripts {
    @Html.Partial("_TaiwanZipCode")
    <script>
        $(document).ready(function () {
            var Message = '@Html.Raw(HttpUtility.JavaScriptStringEncode((string)@TempData["message"]))';
            if (Message != '') {
                showDialog(Message, false);
             }

            $("#Create").click(function () {
                PackageEvent('', true);
            });

            var options = {
                CityID: '#CityDDL',
                CountyID: '#CountyDDL'
            };
            TaiwanZipCode.Settings(options);

        });
        function PackageEvent(uid, createOrUpdat)
        {
            var dataType = '@DataAction.Create';
            var select_CreateTime = $("#select_CreateTime").val();
            var select_TitleName = $("#select_TitleName").val();
            var select_HtmlContext = $("#select_HtmlContext").val();
            var select_StartDate = $("#select_StartDate").val();
            var select_EndDate = $("#select_EndDate").val();

            var url = '@Url.Action("ActivitiesMain", "Activity")'+'?guid=' + uid +
                '&selectCreateTime=' + select_CreateTime + '&selectTitleName=' + select_TitleName +
                '&selectHtmlContext=' + select_HtmlContext + '&selectStartDate=' + select_StartDate +
                '&selectEndDate=' + select_EndDate +
                '&pages=' + @Model.page+ '&ActionType=';
            if (!createOrUpdat) // True = Create; False = Update
            {
                dataType = '@DataAction.Update';
            }
            url += dataType;

            window.location.href = url;
        }
    </script>
}

BackMeow/Views/Activity/ActivitiesMain.cshtml
@model BackMeow.Models.ViewModel.ActitiesDetailViewModel
@{
    ViewBag.Title = "ActivitiesMain";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ActivitiesMain</h2>
@using (Html.BeginForm("ActivitiesMain", "Activity", FormMethod.Post,
    new
    {
        @class = "form-horizontal",
        role = "form",
        enctype = "multipart/form-data",
        id = "ActivitiesMainForm"
    }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-12">
            <!-- PANEL DEFAULT -->
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">活動紀錄 </h3>
                </div>
            </div>
            <!-- END PANEL DEFAULT -->
        </div>
    </div>
    <input type="hidden" name="actions" value="@TempData["DataAction"]" />
    @Html.HiddenFor(s => s.ActivityID)
    @Html.HiddenFor(s => s.PicGroupID)
    <div class="panel-body">
        @Html.NoteSite()
    </div>
    <div class="panel-body">
        @Html.RequiredLabel(@Html.DisplayNameFor(mode => mode.Status).ToString())
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Status)
                @Html.ValidationMessageFor(x => x.Status, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="panel-body">
        @Html.DisplayNameFor(mode => mode.TitleName)
        <div class="col-md-8">
            <input type="text" class="form-control" value="@Model.TitleName" name="TitleName" placeholder="請輸入 @Html.DisplayNameFor(model => model.TitleName)" />
        </div>
    </div>
    <div class="panel-body">
        @Html.RequiredLabel(@Html.DisplayNameFor(mode => mode.Sdate).ToString())
        <div class="col-md-3">
            <input type="text" class="form-control datepicker" onkeydown="return false" value="@Model.Sdate" name="Sdate" placeholder="請輸入 @Html.DisplayNameFor(model => model.Sdate)" />
            @Html.ValidationMessageFor(x => x.Sdate, "", new { @class = "text-danger" })
        </div>
        @Html.RequiredLabel(@Html.DisplayNameFor(mode => mode.Edate).ToString())
        <div class="col-md-3">
            <input type="text" class="form-control datepicker" onkeydown="return false" value="@Model.Edate" name="Edate" placeholder="請輸入 @Html.DisplayNameFor(model => model.Edate)" />
            @Html.ValidationMessageFor(x => x.Edate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="panel-body">
        @Html.LabelFor(model => model.HtmlContext, htmlAttributes: new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(s => s.HtmlContext, new
            {
                htmlAttributes = new
                {
                    placeholder = "請輸入 " + @Html.DisplayNameFor(model => model.HtmlContext),
                    @class = "form-control text-box multi-line",
                    Name = "HtmlContext",
                    @id = "HtmlContext",
                    @rows = 15,
                    cols = 35
                }
            })
        </div>
    </div>
    <div class="panel-body">
        @Html.LabelFor(model => model.CreateUser, htmlAttributes: new { @class = "col-md-2 control-label" })
        <div class="col-md-3">
            @Html.DisplayFor(model => model.CreateUser)
            @Html.HiddenFor(model => model.CreateUser)
        </div>
        @Html.LabelFor(model => model.CreateTime, htmlAttributes: new { @class = "col-md-2 control-label" })
        <div class="col-md-3">
            @Html.DisplayFor(model => model.CreateTime)
            @Html.HiddenFor(model => model.CreateTime)
        </div>
    </div>
    <div class="panel-body">
        @Html.LabelFor(model => model.CreateUser, htmlAttributes: new { @class = "col-md-2 control-label" })
        <div class="col-md-3">
            @Html.DisplayFor(model => model.CreateUser)
            @Html.HiddenFor(model => model.CreateUser)
        </div>
        @Html.LabelFor(model => model.CreateTime, htmlAttributes: new { @class = "col-md-2 control-label" })
        <div class="col-md-3">
            @Html.DisplayFor(model => model.CreateTime)
            @Html.HiddenFor(model => model.CreateTime)
        </div>
    </div>
    <div class="panel-body">
        @Html.LabelFor(model => model.UpdateUser, htmlAttributes: new { @class = "col-md-2 control-label" })
        <div class="col-md-3">
            @Html.DisplayFor(model => model.UpdateUser)
            @Html.HiddenFor(model => model.UpdateUser)
        </div>
        @Html.LabelFor(model => model.UpdateTime, htmlAttributes: new { @class = "col-md-2 control-label" })
        <div class="col-md-3">
            @Html.DisplayFor(model => model.UpdateTime)
            @Html.HiddenFor(model => model.UpdateTime)
        </div>
    </div>
    <div class="panel-body">
        <div class="col-md-2">
        </div>
        <div class="col-md-2">
            <input type="file" name="upload" id="upload" accept="image/gif,image/jpeg,image/jpg,image/png,image/svg" multiple />
        </div>
    </div>
    <div class="panel-body" id="ReloadBlock">
        @*@Html.Partial("_UploadFiles", Model.picInfo)*@
        @Html.Partial("_UploadFiles", Model.picInfo)
        @*@{
            Html.RenderPartial("_UploadFiles", Model.picInfo);
            }*@
    </div>
    <div class="panel-body">
        <div class="col-md-2">
        </div>
        <div class="col-md-3">
            <input type="button" id="Save" class="btn btn-success" value="儲存" />
            <button type="button" class="btn btn-default"
                    onclick="location.href='@Url.Action("ActivitiesList", "Activity", new { })'">
                返回
            </button>
        </div>
    </div>
}
@section Scripts {
    <script>
        $("#Save").click(function () {
            //$("#ulList").empty();
            var fp = $("#upload");
            var lg = fp[0].files.length; // get length
            var items = fp[0].files;
            //var fragment = "";
            var CheckFile = true;
            if (lg > 0) {
                for (var i = 0; i < lg; i++) {
                    var fileName = items[i].name; // get file name
                    var fileSize = items[i].size; // get file size
                    var fileType = items[i].type; // get file type
                    var new1 = filterStr(fileName);
                    //fragment += "<li>" + fileName + " (<b>" +
                    //    fileSize + "</b> bytes) - Type :" + fileType + "特殊符號取代名稱=" + new1 + "</li>";
                    if (!checkFileName(fileName)) {
                        CheckFile = false;
                    }
                }
                //$("#ulList").append(fragment);
            }
            if (CheckFile) {
                $("#ActivitiesMainForm").submit();
            }

        })
    </script>
}

BackMeow/Views/Activity/_ActivitiesList.cshtml
@using StoreDB.Enum;
@model PagedList.IPagedList<BackMeow.Models.ViewModel.ActitiesListContentViewModel>

<table class="table table-bordered table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().TitleName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().HtmlContext)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().STime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().ETime)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TitleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HtmlContext)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.STime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ETime)
            </td>
            <td style="width:18%">
                <button type="button" name="Detail" class="btn btn-primary btn-toastr"
                        onclick="PackageEvent('@item.ActitiesID',false);">
                    明細
                </button>
                <button type="button" class="btn btn-danger">刪除</button>
            </td>
        </tr>
    }
</table>